# Use postgres/example user/password credentials
version: '3.3'

# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: example

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  # api:
  #   image: 
  #   restart: always
  #   depends_on: 
  #     - db
  #   image: miiboard-service:0.1
  #   ports:
  #     - 8081:8081

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
volumes:
    db_data: {}